FROM rust:latest

RUN apt update -y

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&\
apt-get install -y nodejs

RUN apt install git -y

RUN echo 'deb http://download.opensuse.org/repositories/shells:/fish/Debian_11/ /' | tee /etc/apt/sources.list.d/shells:fish.list
RUN curl -fsSL https://download.opensuse.org/repositories/shells:fish/Debian_11/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/shells_fish.gpg > /dev/null
RUN apt update
RUN apt install -y fish
RUN chsh -s /usr/bin/fish   

RUN apt install -y clang cmake

RUN rustup target add wasm32-unknown-unknown